import { NgModule } from '@angular/core';
import {
  NbAccordionModule,
  NbAutocompleteModule,
  NbBadgeModule,
  NbButtonModule,
  NbCalendarModule,
  NbChatModule,
  NbFormFieldModule,
  NbPopoverModule,
  NbSearchModule,
  NbStepperModule,
  NbTagModule,
  NbTimepickerModule,
  NbToggleModule,
  NbTreeGridModule,
  NbUserModule,
  NbWindowModule,
} from '@nebular/theme';
import { NbCardModule } from '@nebular/theme';
import { NbCheckboxModule } from '@nebular/theme';
import { NbContextMenuModule } from '@nebular/theme';
import { NbDatepickerModule } from '@nebular/theme';
import { NbDialogModule } from '@nebular/theme';
import { NbIconModule } from '@nebular/theme';
import { NbInputModule } from '@nebular/theme';
import { NbLayoutModule } from '@nebular/theme';
import { NbListModule } from '@nebular/theme';
import { NbMenuModule } from '@nebular/theme';
import { NbProgressBarModule } from '@nebular/theme';
import { NbRadioModule } from '@nebular/theme';
import { NbSelectModule } from '@nebular/theme';
import { NbSidebarModule } from '@nebular/theme';
import { NbSpinnerModule } from '@nebular/theme';
import { NbTabsetModule } from '@nebular/theme';
import { NbThemeModule } from '@nebular/theme';
import { NbToastrModule } from '@nebular/theme';
import { NbTooltipModule } from '@nebular/theme';
import { NbActionsModule } from '@nebular/theme';
import { NbAlertModule } from '@nebular/theme';
import { NbOptionModule } from '@nebular/theme';
import { NbDialogConfig } from '@nebular/theme';

@NgModule({
  imports: [
    NbButtonModule,
    NbCardModule,
    NbCheckboxModule,
    NbContextMenuModule,
    NbDatepickerModule,
    NbDialogModule,
    NbIconModule,
    NbInputModule,
    NbLayoutModule,
    NbListModule,
    NbMenuModule,
    NbProgressBarModule,
    NbRadioModule,
    NbSelectModule,
    NbSidebarModule,
    NbSpinnerModule,
    NbTabsetModule,
    NbThemeModule,
    NbToastrModule,
    NbTooltipModule,
    NbAccordionModule,
    NbAutocompleteModule,
    NbBadgeModule,
    NbCalendarModule,
    NbCardModule,
    NbChatModule,
    NbCheckboxModule,
    NbContextMenuModule,
    NbDatepickerModule,
    NbDialogModule,
    NbFormFieldModule,
    NbInputModule,
    NbListModule,
    NbMenuModule,
    NbPopoverModule,
    NbProgressBarModule,
    NbRadioModule,
    NbSearchModule,
    NbSelectModule,
    NbSpinnerModule,
    NbStepperModule,
    NbTabsetModule,
    NbTagModule,
    NbTimepickerModule,
    NbToggleModule,
    NbTreeGridModule,
    NbUserModule,
    NbWindowModule,
    NbActionsModule,
    NbAlertModule,
    NbBadgeModule,
    NbChatModule,
    NbContextMenuModule,
    NbDatepickerModule,
    NbDialogModule,
    NbInputModule,
    NbMenuModule,
    NbPopoverModule,
    NbSearchModule,
    NbSpinnerModule,
    NbStepperModule,
    NbTimepickerModule,
    NbToggleModule,
    NbTreeGridModule,
    NbUserModule,
    NbWindowModule,
  ],
  exports: [
    NbButtonModule,
    NbCardModule,
    NbCheckboxModule,
    NbContextMenuModule,
    NbDatepickerModule,
    NbDialogModule,
    NbIconModule,
    NbInputModule,
    NbLayoutModule,
    NbListModule,
    NbProgressBarModule,
    NbRadioModule,
    NbSelectModule,
    NbSidebarModule,
    NbSpinnerModule,
    NbTabsetModule,
    NbThemeModule,
    NbToastrModule,
    NbTooltipModule,
    NbButtonModule,
    NbCardModule,
    NbCheckboxModule,
    NbContextMenuModule,
    NbDatepickerModule,
    NbDialogModule,
    NbIconModule,
    NbInputModule,
    NbLayoutModule,
    NbListModule,
    NbMenuModule,
    NbProgressBarModule,
    NbRadioModule,
    NbSelectModule,
    NbSidebarModule,
    NbSpinnerModule,
    NbTabsetModule,
    NbThemeModule,
    NbToastrModule,
    NbTooltipModule,
    NbAccordionModule,
    NbAutocompleteModule,
    NbBadgeModule,
    NbCalendarModule,
    NbCardModule,
    NbChatModule,
    NbCheckboxModule,
    NbContextMenuModule,
    NbDatepickerModule,
    NbDialogModule,
    NbFormFieldModule,
    NbInputModule,
    NbListModule,
    NbMenuModule,
    NbPopoverModule,
    NbProgressBarModule,
    NbRadioModule,
    NbSearchModule,
    NbSelectModule,
    NbSpinnerModule,
    NbStepperModule,
    NbTabsetModule,
    NbTagModule,
    NbTimepickerModule,
    NbToggleModule,
    NbTreeGridModule,
    NbUserModule,
    NbWindowModule,
    NbActionsModule,
    NbAlertModule,
    NbBadgeModule,
    NbChatModule,
    NbContextMenuModule,
    NbDatepickerModule,
    NbDialogModule,
    NbInputModule,
    NbMenuModule,
    NbPopoverModule,
    NbSearchModule,
    NbSpinnerModule,
    NbStepperModule,
    NbTimepickerModule,
    NbToggleModule,
    NbTreeGridModule,
    NbUserModule,
    NbWindowModule,
  ],
})
export class NebularLibraryModule {}
